language: cpp
os: linux
compiler: gcc
dist: bionic

addons:
  apt:
    packages: lcov

script:
  - mkdir build && cd build
  - cmake -DBUILD_TESTING=ON -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest . $(nproc) 

after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --no-external --output-file coverage.info
# output coverage data for debugging (optional)
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"