language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.8, g++-4.8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.8 && CXX=g++-4.8 && CXXFLAGS=-m32"
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.8, g++-4.8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.8 && CXX=g++-4.8 && CXXFLAGS=-m64"

    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.9, g++-4.9-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.9 && CXX=g++-4.9 && CXXFLAGS=-m32"
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.9, g++-4.9-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.9 && CXX=g++-4.9 && CXXFLAGS=-m64"

    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-5, g++-5-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-5 && CXX=g++-5 && CXXFLAGS=-m32"
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-5, g++-5-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-5 && CXX=g++-5 && CXXFLAGS=-m64"

    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-6, g++-6-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-6 && CXX=g++-6 && CXXFLAGS=-m32"
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-6, g++-6-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-6 && CXX=g++-6 && CXXFLAGS=-m64"

    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-7, g++-7-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-m32"
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-7, g++-7-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-m64"

    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-7, g++-7-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Release && CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-m32"
    - os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-7, g++-7-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Release && CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-m64"

    - os: osx
      osx_image: xcode7.3
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m32"
    - os: osx
      osx_image: xcode7.3
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m64"

    - os: osx
      osx_image: xcode8
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m32"
    - os: osx
      osx_image: xcode8
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m64"

    - os: osx
      osx_image: xcode9
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m32"
    - os: osx
      osx_image: xcode9
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m64"

    - os: osx
      osx_image: xcode9
      env: BUILD_MATRIX="BUILD_TYPE=Release && CXXFLAGS=-m32"
    - os: osx
      osx_image: xcode9
      env: BUILD_MATRIX="BUILD_TYPE=Release && CXXFLAGS=-m64"

before_install:
  - eval "$BUILD_MATRIX"

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CMAKE_PACKAGE="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
      mkdir -p deps/cmake
      wget --no-check-certificate --quiet -O - $CMAKE_PACKAGE | tar --strip-components=1 -xz -C deps/cmake
      export PATH=$TRAVIS_BUILD_DIR/deps/cmake/bin:$PATH
    else
      brew update
      brew outdated cmake || brew upgrade cmake
    fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DASMJIT_BUILD_TEST=1
  - cd ..

script:
  - cd build
  - make
  - cd ..

  - ./build/asmjit_test_unit
  - ./build/asmjit_test_opcode > /dev/null
  - ./build/asmjit_test_x86_asm
  - ./build/asmjit_test_x86_cc

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_unit; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_x86_asm; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_x86_cc; fi;
